""" 
RSV-A Sequencing Analysis Pipeline.
Author: Will Hannon 
"""

#### ----------------------- Imports ----------------------- ####

import pandas as pd 
from os.path import join

#### -------------------- Configuration -------------------- ####

configfile: "configuration/pipeline.yml"

#### ----------------------- Targets ----------------------- ####
# sample_df = pd.read_csv(config['samples'])

rule all:
    input:
        expand("results/reference/{gene}.fasta", gene=config['genes'])

#### ------------------------ Rules ------------------------ ####

rule clean:
    shell:
        """
        rm -rf logs/
        rm -rf tmp/
        rm -f slurm*.out
        """


rule make_gene_reference:
    output:
        outpath = "results/reference/{gene}.fasta"
    params:
        fasta_url = config['ref'],
        gff_url = config['gff']
    shell:
        """
        python workflow/scripts/parse_gene.py {params.fasta_url} {params.gff_url} {wildcards.gene} {output.outpath}
        """