name: rsva-sequencing

channels:
  - conda-forge
  - defaults
  - bioconda

dependencies:
  - jupyterlab
  - python=3.11
  - snakemake=8.14
  - biopython
  - pip
  - pip:
    - pandas>=2.2
    - altair