name: antibody-passaging

channels:
  - conda-forge
  - bioconda

dependencies:
  - jupyterlab
  - python=3.11
  - snakemake=8.14
  - snakemake-executor-plugin-slurm
  - biopython
  - pip
  - pip:
    - pandas>=2.2
    - altair
