executor: slurm
latency-wait: 60
jobs: 100
slurm-init-seconds-before-status-checks: 20

default-resources:
  slurm_account: bloom_j
  partition: campus-new
  runtime: 10800
  cpus_per_task: 1
  mem_mb: 4000

set-resources:
  align_stock_with_bwa:
    cpus_per_task: 8
  align_all_reads_with_bwa:
    cpus_per_task: 8