#### ============== snakemake configuration file ============== ####

# Configuration file for RSV-A deep sequencing analysis pipeline
# Author: William Hannon

#### ------------------------- Samples ------------------------ ####

samples: configuration/samples.csv

#### ------------------------- Genomes ------------------------ ####

RSV-A:
  ref: configuration/reference/KT992094_truncated.fasta
  gff: configuration/reference/KT992094_truncated.gff
HMPV:  
  ref: configuration/reference/HMPV.fasta
  gff: configuration/reference/HMPV.gff

#### ------------------------- Params ------------------------ ####

threads:
  max_cpu: 8

min_pval: 0.05
min_depth: 200
min_freq: 0.03

#### -------------------------- Dirs ------------------------- ####

reference_dir: results/reference
fastq_dir: results/fastq
trim_dir: results/trimmed
consensus_dir: results/consensus
align_dir: results/aligned
variants_dir: results/variants
qc_dir: results/qc
coverage_dir: results/coverage
summary_dir: results/summary
