#### ============== snakemake configuration file ============== ####

# Configuration file for RSV-A deep sequencing analysis pipeline
# Author: William Hannon

#### ------------------------- Samples ------------------------ ####

samples: configuration/samples.csv

#### ------------------------- Genomes ------------------------ ####

ref: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/856/445/GCF_000856445.1_ViralProj15004/GCF_000856445.1_ViralProj15004_genomic.fna.gz
gff: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/856/445/GCF_000856445.1_ViralProj15004/GCF_000856445.1_ViralProj15004_genomic.gff.gz
genes: ['F']

#### -------------------------- Util -------------------------- ####

#### ------------------------- Params ------------------------ ####

threads:
  max_cpu: 8

#### -------------------------- Dirs ------------------------- ####

fastq_dir: results/fastq
trim_dir: results/trimmed
qc_dir: results/qc

