#### ============== snakemake configuration file ============== ####

# Configuration file for RSV-A deep sequencing analysis pipeline
# Author: William Hannon

#### ------------------------- Samples ------------------------ ####

samples: configuration/samples.csv

#### ------------------------- Genomes ------------------------ ####

ref: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/856/445/GCF_000856445.1_ViralProj15004/GCF_000856445.1_ViralProj15004_genomic.fna.gz
gff: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/856/445/GCF_000856445.1_ViralProj15004/GCF_000856445.1_ViralProj15004_genomic.gff.gz

#### -------------------------- Util -------------------------- ####

#### ------------------------- Params ------------------------ ####

threads:
  max_cpu: 8

#### -------------------------- Dirs ------------------------- ####

reference_dir: results/reference
fastq_dir: results/fastq
trim_dir: results/trimmed
consensus_dir: results/consensus
align_dir: results/aligned
variants_dir: results/variants
qc_dir: results/qc
coverage_dir: results/coverage
